In [14]:
import numpy as np


In [15]:
import matplotlib.pyplot as plt

In [27]:
employee_codes = np.array([101,102,103,104,105])
salaries = np.array([10000,20000,30000,40000,50000])
performance = np.array([1,3.5,4,2,2.7])
attendance = np.array([20,28,25,15,10])
print(employee_codes)
print(salaries)
print(performance)
print(attendance)

[101 102 103 104 105]
[10000 20000 30000 40000 50000]
[1.  3.5 4.  2.  2.7]
[20 28 25 15 10]


In [37]:
def update_attendance(emp_code,new_attendance):
    index = np.where(employee_codes == emp_code)[0][0]
    attendance_index = new_attendance

In [19]:
def change_performance(emp_code,new_performance):
    index = np.where(employee_codes == emp_codee)[0][0]
    performance_index = new_performance

In [38]:
def salary_statistics():
    avg_salary = np.mean(salaries)
    max_salary = np.max(salaries)
    min_salary = np.min(salaries)
    return avg_salary, max_salary, min_salary

In [ ]:
update_attendance(102,20)